# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='switcher.Context')),
            ],
        ),
        migrations.RemoveField(
            model_name='mix',
            name='app',
        ),
        migrations.RemoveField(
            model_name='placementmappings',
            name='mix',
        ),
        migrations.AddField(
            model_name='placementmappings',
            name='app',
            field=models.ForeignKey(default='com.ms.wechat', on_delete=django.db.models.deletion.CASCADE, related_name='placement_mappings', to='switcher.AppNode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementmappings',
            name='extra',
            field=models.TextField(default='aabbccddd1123123123123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementmappings',
            name='sid',
            field=models.IntegerField(default=9080123),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mix',
        ),
    ]
