# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0002_auto_20170527_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sid', models.IntegerField()),
                ('extra', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='switcher.AppNode')),
            ],
        ),
        migrations.RemoveField(
            model_name='placementmappings',
            name='app',
        ),
        migrations.DeleteModel(
            name='PlacementMappings',
        ),
    ]
