# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0004_auto_20170531_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='shadow',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
