# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0007_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='action',
            new_name='install_action',
        ),
        migrations.AddField(
            model_name='member',
            name='open_action',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
