# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0008_auto_20170613_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='icon_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_url',
            field=models.TextField(),
        ),
    ]
