# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0009_auto_20170613_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('pkg_name', models.CharField(max_length=255)),
                ('version_name', models.CharField(max_length=255)),
                ('version_code', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('signatures', models.TextField()),
                ('extra', models.TextField()),
            ],
        ),
    ]
