# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0012_auto_20170620_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crackcontext',
            name='crack_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='switcher.CrackNode'),
        ),
        migrations.AlterField(
            model_name='crackcontext',
            name='extra',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='crackplacement',
            name='crack_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='switcher.CrackNode'),
        ),
    ]
