# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0013_auto_20170621_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='promotable',
            field=models.BooleanField(default=True),
        ),
    ]
