# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0014_member_promotable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='promotable',
            new_name='public',
        ),
    ]
