# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0016_member_latest_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crackcontext',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='crackcontext',
            name='platform',
        ),
        migrations.AlterField(
            model_name='crackplacement',
            name='extra',
            field=models.TextField(blank=True, default=''),
        ),
    ]
