# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0017_auto_20170628_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crackplacement',
            name='extra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
