# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0019_auto_20170630_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crackcontext',
            old_name='label',
            new_name='l',
        ),
        migrations.RenameField(
            model_name='crackcontext',
            old_name='pkg_name',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='crackcontext',
            old_name='signatures',
            new_name='sg',
        ),
        migrations.RenameField(
            model_name='crackcontext',
            old_name='version_code',
            new_name='vc',
        ),
        migrations.RenameField(
            model_name='crackcontext',
            old_name='version_name',
            new_name='vn',
        ),
        migrations.RenameField(
            model_name='cracknode',
            old_name='pkg_name',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='crackplacement',
            old_name='extra',
            new_name='e',
        ),
        migrations.RenameField(
            model_name='crackplacement',
            old_name='max_times',
            new_name='mt',
        ),
        migrations.RenameField(
            model_name='crackplacement',
            old_name='sid',
            new_name='s',
        ),
        migrations.RenameField(
            model_name='crackplacement',
            old_name='start_times',
            new_name='st',
        ),
        migrations.AlterField(
            model_name='crackplacement',
            name='crack_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='switcher.CrackNode'),
        ),
    ]
