# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0021_auto_20170711_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracknode',
            name='ext',
            field=models.IntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='cracknode',
            name='fe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cracknode',
            name='je',
            field=models.BooleanField(default=True),
        ),
    ]
