# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0022_auto_20170719_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='JhContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=255)),
                ('vn', models.CharField(max_length=255)),
                ('vc', models.IntegerField(default=0)),
                ('l', models.CharField(max_length=255)),
                ('sg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JhMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=255)),
                ('v', models.CharField(max_length=255)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='md', to='switcher.JhContext')),
            ],
        ),
        migrations.CreateModel(
            name='JhNode',
            fields=[
                ('p', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext', models.IntegerField(default=86400)),
                ('pro', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='jhcontext',
            name='jh_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='switcher.JhNode'),
        ),
    ]
