# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0023_auto_20170719_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jhmetadata',
            old_name='n',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='jhmetadata',
            old_name='v',
            new_name='vl',
        ),
    ]
