# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0024_auto_20170719_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cracknode',
            old_name='je',
            new_name='ae',
        ),
        migrations.RenameField(
            model_name='cracknode',
            old_name='ext',
            new_name='et',
        ),
        migrations.RemoveField(
            model_name='jhnode',
            name='ext',
        ),
    ]
