# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0026_cracknode_je'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracknode',
            name='ii',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='cracknode',
            name='oe',
            field=models.IntegerField(default=True),
        ),
    ]
