# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0027_auto_20170727_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracknode',
            name='oe',
            field=models.BooleanField(default=True),
        ),
    ]
