# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0028_auto_20170727_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracknode',
            name='cs',
            field=models.IntegerField(default=0),
        ),
    ]
