# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0030_sdknode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdknode',
            old_name='l',
            new_name='lk',
        ),
    ]
