# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0031_auto_20170817_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracknode',
            name='cd',
            field=models.IntegerField(default=0),
        ),
    ]
