# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switcher', '0032_cracknode_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracknode',
            name='cd',
            field=models.IntegerField(default=1000),
        ),
    ]
