# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('log_time', models.IntegerField(default=0)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('android_id', models.CharField(max_length=255)),
                ('google_ad_id', models.CharField(max_length=255)),
                ('referer', models.CharField(max_length=255)),
                ('time_offset', models.IntegerField(default=0)),
                ('locale', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='statistic.Stat'),
        ),
    ]
